using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEditor;
using MCPForUnity.Editor.Tools.ProjectSnapshot;
using MCPForUnity.Editor.Helpers;

namespace MCPForUnity.Editor.Tools
{
    /// <summary>
    /// MCP tool interface for Project Snapshot.
    /// Delegates actual generation to ProjectSnapshotGenerator.
    /// Provides read-only access to generated snapshots.
    /// </summary>
    [McpForUnityTool("project_snapshot", Description = "Generates AI-friendly project snapshot with architecture and directory structure. Use read_snapshot to quickly access existing snapshots.")]
    public static class ProjectSnapshotTool
    {
        /// <summary>
        /// Main handler for the project_snapshot command.
        /// Generates or regenerates the project snapshot.
        /// </summary>
        public static object HandleCommand(JObject @params)
        {
            // Check if this is a read-only request
            if (@params["action"] != null && @params["action"].ToString() == "read")
            {
                return HandleRead(@params);
            }

            // Check if this is a status request
            if (@params["action"] != null && @params["action"].ToString() == "status")
            {
                return HandleStatus(@params);
            }

            // Default: generate snapshot
            return HandleGenerate(@params);
        }

        /// <summary>
        /// Handles snapshot generation.
        /// </summary>
        private static object HandleGenerate(JObject @params)
        {
            try
            {
                var settings = ProjectSnapshotSettings.Instance;
                var options = settings?.ToOptions() ?? new SnapshotOptions();

                // Override with explicit parameters if provided
                options = ApplyOverrides(options, @params);

                // Check if user wants to bypass auto-generated snapshot
                bool forceRegenerate = @params["force_regenerate"]?.Value<bool>() ?? false;
                if (forceRegenerate)
                {
                    options.ForceRegenerate = true;
                }

                var result = ProjectSnapshotGenerator.Generate(options, isAutoGenerated: false);

                if (result == null)
                {
                    return new ErrorResponse("Generation already in progress. Please wait.");
                }

                if (!result.Success)
                {
                    return new ErrorResponse($"Generation failed: {result.ErrorMessage}");
                }

                var response = new Dictionary<string, object>
                {
                    ["output_path"] = result.OutputPath,
                    ["word_count"] = result.WordCount,
                    ["generation_time_ms"] = result.GenerationTimeMs,
                    ["from_cache"] = result.FromCache,
                    ["sections"] = new[] { "Core Architecture", "Directory Map", "Data Schema" }
                };

                if (!string.IsNullOrEmpty(result.DependenciesPath))
                {
                    response["dependencies_path"] = result.DependenciesPath;
                    response["dependencies_word_count"] = result.DependenciesWordCount;
                }

                if (result.IndexGenerated)
                {
                    response["index_generated"] = true;
                }

                return new SuccessResponse($"Project snapshot generated at: {result.OutputPath}", response);
            }
            catch (Exception e)
            {
                return new ErrorResponse($"Error generating project snapshot: {e.Message}");
            }
        }

        /// <summary>
        /// Handles snapshot reading (returns existing snapshot content).
        /// </summary>
        private static object HandleRead(JObject @params)
        {
            try
            {
                var settings = ProjectSnapshotSettings.Instance;
                var snapshotPath = @params["snapshot_path"]?.ToString() ?? settings?.outputPath ?? "Project_Snapshot.md";

                var content = ProjectSnapshotGenerator.ReadSnapshotContent(snapshotPath);

                if (content == null)
                {
                    return new ErrorResponse($"Snapshot not found at: {snapshotPath}. Use action='generate' to create one.");
                }

                var status = ProjectSnapshotGenerator.GetStatus(
                    snapshotPath,
                    settings?.dependenciesOutputPath ?? "Asset_Dependencies.md"
                );

                return new SuccessResponse($"Snapshot read from: {snapshotPath}", new Dictionary<string, object>
                {
                    ["content"] = content,
                    ["path"] = snapshotPath,
                    ["exists"] = true,
                    ["last_generated"] = status.LastGenerated,
                    ["age_minutes"] = status.AgeMinutes,
                    ["is_dirty"] = status.IsDirty
                });
            }
            catch (Exception e)
            {
                return new ErrorResponse($"Error reading snapshot: {e.Message}");
            }
        }

        /// <summary>
        /// Handles snapshot status check.
        /// </summary>
        private static object HandleStatus(JObject @params)
        {
            try
            {
                var settings = ProjectSnapshotSettings.Instance;
                var snapshotPath = @params["snapshot_path"]?.ToString() ?? settings?.outputPath ?? "Project_Snapshot.md";
                var dependenciesPath = settings?.dependenciesOutputPath ?? "Asset_Dependencies.md";

                var status = ProjectSnapshotGenerator.GetStatus(snapshotPath, dependenciesPath);

                return new SuccessResponse("Snapshot status retrieved", new Dictionary<string, object>
                {
                    ["exists"] = status.Exists,
                    ["dependencies_exist"] = status.DependenciesExist,
                    ["last_generated"] = status.LastGenerated,
                    ["age_minutes"] = Math.Round(status.AgeMinutes, 1),
                    ["is_dirty"] = status.IsDirty,
                    ["recommendation"] = status.Recommendation ?? (status.IsDirty ? "Consider regenerating" : "Snapshot is up to date")
                });
            }
            catch (Exception e)
            {
                return new ErrorResponse($"Error checking status: {e.Message}");
            }
        }

        /// <summary>
        /// Applies parameter overrides to the options.
        /// </summary>
        private static SnapshotOptions ApplyOverrides(SnapshotOptions options, JObject @params)
        {
            if (@params == null) return options;

            if (@params["include_packages"] != null)
                options.IncludePackages = @params["include_packages"].Value<bool>();

            if (@params["max_depth"] != null)
                options.MaxDepth = @params["max_depth"].Value<int>();

            if (@params["include_dependencies"] != null)
                options.IncludeDependencies = @params["include_dependencies"].Value<bool>();

            if (@params["include_data_schemas"] != null)
                options.IncludeDataSchemas = @params["include_data_schemas"].Value<bool>();

            if (@params["output_path"] != null)
                options.OutputPath = @params["output_path"].ToString();

            if (@params["use_cache"] != null)
                options.UseCache = @params["use_cache"].Value<bool>();

            if (@params["force_regenerate"] != null)
                options.ForceRegenerate = @params["force_regenerate"].Value<bool>();

            if (@params["separate_dependencies_file"] != null)
                options.SeparateDependenciesFile = @params["separate_dependencies_file"].Value<bool>();

            if (@params["generate_dependencies_file"] != null)
                options.SeparateDependenciesFile = @params["generate_dependencies_file"].Value<bool>();

            if (@params["dependencies_output_path"] != null)
                options.DependenciesOutputPath = @params["dependencies_output_path"].ToString();

            if (@params["generate_index"] != null)
                options.GenerateIndex = @params["generate_index"].Value<bool>();

            if (@params["max_prefabs_to_analyze"] != null)
                options.MaxPrefabsToAnalyze = @params["max_prefabs_to_analyze"].Value<int>();

            if (@params["max_core_prefabs"] != null)
                options.MaxCorePrefabs = @params["max_core_prefabs"].Value<int>();

            if (@params["max_dependencies_per_prefab"] != null)
                options.MaxDependenciesPerPrefab = @params["max_dependencies_per_prefab"].Value<int>();

            if (@params["max_manager_classes"] != null)
                options.MaxManagerClasses = @params["max_manager_classes"].Value<int>();

            if (@params["max_scriptable_objects"] != null)
                options.MaxScriptableObjects = @params["max_scriptable_objects"].Value<int>();

            if (@params["max_files_to_scan"] != null)
                options.MaxFilesToScan = @params["max_files_to_scan"].Value<int>();

            if (@params["max_json_examples"] != null)
                options.MaxJsonExamples = @params["max_json_examples"].Value<int>();

            return options;
        }
    }
}
