"""Project snapshot tool - read AI-friendly project overview.

The snapshot is automatically generated by Unity after script compilation.
Supports tiered detail levels for efficient AI understanding.
"""

from typing import Annotated, Any, Literal

from fastmcp import Context
from mcp.types import ToolAnnotations

from services.registry import mcp_for_unity_tool
from services.tools import get_unity_instance_from_context
from services.tools.utils import coerce_bool
from transport.unity_transport import send_with_unity_instance
from transport.legacy.unity_connection import async_send_command_with_retry


DetailLevel = Literal["basic", "structure", "verbose"]


@mcp_for_unity_tool(
    description=(
        "Get Unity project snapshot with tiered detail levels. "
        "basic: project overview (Unity version, render pipeline, scale). "
        "structure: entry points, system categories, core directory structure. "
        "verbose: full context including complete file tree, data schema, dependencies. "
        "The snapshot is automatically maintained by Unity and regenerated after script compilation."
    ),
    annotations=ToolAnnotations(title="Project Snapshot"),
)
async def get_project_snapshot(
    ctx: Context,
    detail_level: Annotated[DetailLevel, "Detail level: basic (overview), structure (entry points & systems), verbose (full context). Default: basic."] | None = None,
    force_refresh: Annotated[bool, "Force regeneration of snapshot (slower, ensures fresh data). Default: false."] | None = None,
    include_dependencies: Annotated[bool, "Include dependencies file content (only for verbose level, can be large). Default: false."] | None = None,
) -> dict[str, Any]:
    """Get the auto-generated project snapshot.

    The snapshot is automatically generated by Unity after script compilation.
    No manual generation is needed - Unity keeps it up to date.

    Args:
        detail_level: Level of detail to return
            - basic: Project overview (Unity version, render pipeline, scale, key packages)
            - structure: Entry points, system categories, core directory structure
            - verbose: Full context including complete file tree, data schema, dependencies
        force_refresh: Force regeneration (slower, ensures fresh data)
        include_dependencies: Include dependencies file (verbose level only, can be large)

    Returns:
        Dict with keys:
        - success: bool - Operation result
        - message: str - Status message
        - data: dict with
            - metadata: dict - Generation information
                - generated_at: str - ISO timestamp
                - unity_version: str - Unity version
                - render_pipeline: str - URP/HDRP/Built-in
                - project_name: str - Project name
                - age_minutes: float - Snapshot age in minutes
                - is_compiling: bool - Whether Unity is compiling
                - script_count: int - Number of scripts
                - scene_count: int - Number of scenes
            - content: str - Snapshot content at requested detail level
            - dependencies_content: str | null - Dependencies file (if requested and exists)
            - char_count: int - Content length in characters
    """
    unity_instance = get_unity_instance_from_context(ctx)

    try:
        coerced_detail = detail_level or "basic"
        coerced_force = coerce_bool(force_refresh, default=False)
        coerced_include_deps = coerce_bool(include_dependencies, default=False)

        params: dict[str, Any] = {
            "detail_level": coerced_detail,
            "force_refresh": coerced_force,
            "include_dependencies": coerced_include_deps,
        }

        response = await send_with_unity_instance(
            async_send_command_with_retry,
            unity_instance,
            "get_project_snapshot",
            params,
        )

        if isinstance(response, dict) and response.get("success"):
            data = response.get("data", {})

            return {
                "success": True,
                "message": response.get("message", "Snapshot retrieved."),
                "data": {
                    "metadata": data.get("metadata", {}),
                    "content": data.get("content", ""),
                    "dependencies_content": data.get("dependencies_content"),
                    "char_count": data.get("char_count", 0),
                }
            }

        return response if isinstance(response, dict) else {"success": False, "message": str(response)}

    except Exception as e:
        return {"success": False, "message": f"Error reading snapshot: {str(e)}"}
