using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;
using UnityEditor;
using Logger = UnityEngine.Debug;

namespace MCPForUnity.Editor.Tools.ProjectSnapshot
{
    /// <summary>
    /// Pure snapshot generation logic, independent of MCP layer.
    /// Can be called by both AutoGenerator and Tool layers.
    /// Provides concurrent execution safety.
    /// </summary>
    public static class ProjectSnapshotGenerator
    {
        private static readonly object _generationLock = new object();
        private static bool _isGenerating = false;

        /// <summary>
        /// Checks if a generation is currently in progress.
        /// </summary>
        public static bool IsGenerating => _isGenerating;

        /// <summary>
        /// Generates the project snapshot with the given options.
        /// Thread-safe - will return null if a generation is already in progress.
        /// </summary>
        public static SnapshotResult Generate(SnapshotOptions options, bool isAutoGenerated = false)
        {
            // Quick exit if already generating
            if (_isGenerating)
            {
                Logger.LogWarning("[ProjectSnapshot] Generation already in progress. Skipping.");
                return null;
            }

            lock (_generationLock)
            {
                // Double-check after acquiring lock
                if (_isGenerating)
                {
                    Logger.LogWarning("[ProjectSnapshot] Generation already in progress. Skipping.");
                    return null;
                }

                _isGenerating = true;
            }

            var stopwatch = Stopwatch.StartNew();
            string logPrefix = isAutoGenerated ? "[ProjectSnapshot-Auto]" : "[ProjectSnapshot]";

            try
            {
                // Check cache if enabled and not forcing regeneration
                bool fromCache = false;
                SnapshotCacheMetadata cacheMetadata = null;

                if (options.UseCache && !options.ForceRegenerate && SnapshotCache.IsCacheValid(options))
                {
                    cacheMetadata = SnapshotCache.LoadMetadata();
                    if (cacheMetadata != null)
                    {
                        fromCache = true;
                        options.ForceRegenerate = false;
                        Logger.Log($"{logPrefix} Using cached snapshot (generated {cacheMetadata.LastGenerated:u})");
                    }
                }

                // Generate main snapshot
                var snapshot = GenerateSnapshotContent(options);
                SaveSnapshot(snapshot, options.OutputPath);

                // Generate dependencies file separately if requested
                string dependenciesPath = null;
                int dependenciesWordCount = 0;
                bool dependenciesGenerated = false;

                if (options.SeparateDependenciesFile && !fromCache)
                {
                    dependenciesPath = options.DependenciesOutputPath;
                    var dependencies = GenerateDependenciesFile(options);
                    dependenciesWordCount = dependencies.Length;
                    SaveSnapshot(dependencies, dependenciesPath);
                    dependenciesGenerated = true;
                }

                // Generate dependency index if requested
                bool indexGenerated = false;
                if (options.GenerateIndex && (dependenciesGenerated || options.IncludeDependencies))
                {
                    var index = new DependencyIndex();
                    index.GenerateIndex(options);
                    index.SaveIndex(options.IndexPath);
                    indexGenerated = true;
                }

                // Generate structured snapshot for efficient AI access
                if (!fromCache)
                {
                    GenerateStructuredSnapshot(options, forceRegenerate: true);
                }

                // Update cache metadata
                var metadata = SnapshotCache.CreateMetadata(options);
                if (dependenciesGenerated)
                {
                    metadata.TotalAssets = AssetRegistryAnalyzer.FindCorePrefabs(options).Count;
                    metadata.TotalPrefabs = metadata.TotalAssets;
                }
                SnapshotCache.SaveMetadata(metadata, options.CachePath);

                stopwatch.Stop();

                if (!isAutoGenerated)
                {
                    Logger.Log($"{logPrefix} Generated in {stopwatch.ElapsedMilliseconds}ms");
                }

                return new SnapshotResult
                {
                    Success = true,
                    OutputPath = options.OutputPath,
                    DependenciesPath = dependenciesPath,
                    WordCount = snapshot.Length,
                    DependenciesWordCount = dependenciesWordCount,
                    GenerationTimeMs = stopwatch.ElapsedMilliseconds,
                    FromCache = fromCache,
                    IndexGenerated = indexGenerated
                };
            }
            catch (Exception e)
            {
                stopwatch.Stop();
                Logger.LogError($"{logPrefix} Error generating snapshot: {e.Message}");
                return new SnapshotResult
                {
                    Success = false,
                    ErrorMessage = e.Message
                };
            }
            finally
            {
                lock (_generationLock)
                {
                    _isGenerating = false;
                }
            }

        }

        /// <summary>
        /// Checks if the snapshot needs regeneration based on dirty state.
        /// </summary>
        public static bool CheckNeedsRegeneration(SnapshotOptions options)
        {
            if (options.ForceRegenerate) return true;

            var cachePath = SnapshotCache.GetCachePath();
            if (!File.Exists(cachePath)) return true;

            var dirtyCheck = SnapshotCache.CheckProjectDirty(options.OutputPath);
            return dirtyCheck.IsDirty;
        }

        /// <summary>
        /// Reads the snapshot content from disk.
        /// Returns null if file doesn't exist.
        /// </summary>
        public static string ReadSnapshotContent(string path)
        {
            var fullPath = Path.Combine(Application.dataPath, "..", path);
            if (!File.Exists(fullPath)) return null;

            try
            {
                return File.ReadAllText(fullPath);
            }
            catch (Exception e)
            {
                Logger.LogError($"[ProjectSnapshot] Error reading snapshot: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// Gets the current status of the snapshot.
        /// </summary>
        public static SnapshotStatus GetStatus(string snapshotPath, string dependenciesPath)
        {
            var result = new SnapshotStatus();

            // Check main snapshot
            var mainFullPath = Path.Combine(Application.dataPath, "..", snapshotPath);
            result.Exists = File.Exists(mainFullPath);

            if (result.Exists)
            {
                result.LastGenerated = File.GetLastWriteTime(mainFullPath);
                result.AgeMinutes = (DateTime.UtcNow - result.LastGenerated.Value).TotalMinutes;
            }

            // Check dependencies file
            var depFullPath = Path.Combine(Application.dataPath, "..", dependenciesPath);
            result.DependenciesExist = File.Exists(depFullPath);

            // Check dirty state
            var dirtyCheck = SnapshotCache.CheckProjectDirty(snapshotPath);
            result.IsDirty = dirtyCheck.IsDirty;
            result.Recommendation = dirtyCheck.Recommendation;

            return result;
        }

        #region Structured Snapshot Support

        private static readonly string StructuredSnapshotPath = "Library/ProjectSnapshot/.structured.json";

        /// <summary>
        /// Generates a structured snapshot with tiered sections for efficient AI access.
        /// Uses the "Golden Template" format with AI-optimized rendering.
        /// </summary>
        public static ProjectSnapshotData GenerateStructuredSnapshot(SnapshotOptions options, bool forceRegenerate = false)
        {
            // Check cache first
            if (!forceRegenerate)
            {
                var cached = LoadStructuredSnapshot();
                if (cached != null)
                {
                    return cached;
                }
            }

            // Generate semantic data using new analyzers
            var metadata = GenerateMetadata(options);
            var identity = ProjectIdentityAnalyzer.Analyze();
            var systems = SystemAnatomyGenerator.Generate();
            var mentalMap = MentalMapGenerator.Generate();

            // Render content using new renderer
            var overviewContent = SnapshotRenderer.RenderSnapshot(metadata, identity, systems, mentalMap);
            var structureContent = GenerateStructureSection(options); // Keep legacy for now
            var deepDiveContent = GenerateDeepDiveSection(options);     // Keep legacy for now

            var data = new ProjectSnapshotData
            {
                Metadata = metadata,
                OverviewSection = overviewContent,
                StructureSection = structureContent,
                DeepDiveSection = deepDiveContent
            };

            // Save to cache
            SaveStructuredSnapshot(data);

            return data;
        }

        /// <summary>
        /// Generates the metadata for the snapshot.
        /// </summary>
        private static SnapshotMetadata GenerateMetadata(SnapshotOptions options)
        {
            var stats = ArchitectureAnalyzer.GetProjectStatistics();
            var renderPipeline = DetectRenderPipeline();

            return new SnapshotMetadata
            {
                GeneratedAt = DateTime.UtcNow.ToString("o"),
                UnityVersion = Application.unityVersion,
                RenderPipeline = renderPipeline,
                ProjectName = PlayerSettings.productName,
                AgeMinutes = 0,
                IsCompiling = EditorApplication.isCompiling,
                ScriptCount = Convert.ToInt32(stats.GetValueOrDefault("total_scripts", 0)),
                SceneCount = Convert.ToInt32(stats.GetValueOrDefault("scenes", 0))
            };
        }

        /// <summary>
        /// Detects the render pipeline type.
        /// </summary>
        private static string DetectRenderPipeline()
        {
#if URP_PRESENT
            return "URP";
#elif HDRP_PRESENT
            return "HDRP";
#else
            return "Built-in";
#endif
        }

        /// <summary>
        /// Generates the overview section (basic level).
        /// Purpose: "What is this project?"
        /// </summary>
        private static string GenerateOverviewSection(SnapshotOptions options)
        {
            var sb = new StringBuilder();

            sb.AppendLine("## Project Overview");
            sb.AppendLine();

            var stats = ArchitectureAnalyzer.GetProjectStatistics();
            var renderPipeline = DetectRenderPipeline();

            sb.AppendLine($"**Unity Version**: {Application.unityVersion}");
            sb.AppendLine($"**Render Pipeline**: {renderPipeline}");
            sb.AppendLine($"**Project Name**: {PlayerSettings.productName}");
            sb.AppendLine();

            int scriptCount = Convert.ToInt32(stats.GetValueOrDefault("total_scripts", 0));
            int sceneCount = Convert.ToInt32(stats.GetValueOrDefault("scenes", 0));
            string scale = scriptCount < 20 ? "Small" : scriptCount < 100 ? "Medium" : "Large";

            sb.AppendLine($"**Project Scale**: {scale} ({scriptCount} scripts, {sceneCount} scenes)");
            sb.AppendLine();

            // Detect project type from naming patterns
            var projectType = InferProjectType(stats);
            if (!string.IsNullOrEmpty(projectType))
            {
                sb.AppendLine($"**Detected Project Type**: {projectType}");
                sb.AppendLine();
            }

            // Key packages
            var keyPackages = DetectKeyPackages();
            if (keyPackages.Count > 0)
            {
                sb.AppendLine("**Key Packages**:");
                foreach (var pkg in keyPackages)
                {
                    sb.AppendLine($"- {pkg}");
                }
                sb.AppendLine();
            }

            return sb.ToString();
        }

        /// <summary>
        /// Infers project type from naming patterns and assets.
        /// </summary>
        private static string InferProjectType(Dictionary<string, object> stats)
        {
            var indicators = new List<(string pattern, string type)>
            {
                ("2D", "2D Game"),
                ("3D", "3D Game"),
                ("UI", "UI/Application"),
                ("Network", "Networked/Multiplayer"),
                ("VR", "VR/XR Application"),
                ("AR", "AR Application")
            };

            // Check scene names and script counts
            int scriptCount = Convert.ToInt32(stats.GetValueOrDefault("total_scripts", 0));

            // Simple heuristic - can be enhanced
            if (scriptCount > 50) return "Medium-Large Game Project";
            if (scriptCount > 20) return "Small-Medium Game Project";
            return "Small Project";
        }

        /// <summary>
        /// Detects key Unity packages in use.
        /// </summary>
        private static List<string> DetectKeyPackages()
        {
            var packages = new List<string>();

            // Check for common packages via type existence
            if (TypeExists("UnityEngine.Cinemachine.CinemachineVirtualCamera"))
                packages.Add("Cinemachine");
            if (TypeExists("UnityEngine.InputSystem.InputAction"))
                packages.Add("Input System");
            if (TypeExists("NavMeshPlus.Components.NavMeshSurface"))
                packages.Add("NavMeshPlus");
            if (TypeExists("Unity.AI.Navigation.NavMesh"))
                packages.Add("AI Navigation");

            return packages;
        }

        private static bool TypeExists(string typeName)
        {
            return Type.GetType(typeName) != null ||
                   System.AppDomain.CurrentDomain.GetAssemblies()
                       .SelectMany(a => a.GetTypes())
                       .Any(t => t.FullName == typeName || t.Name == typeName.Split('.').Last());
        }

        /// <summary>
        /// Generates the structure section (structure level).
        /// Purpose: "Where do I find code?"
        /// </summary>
        private static string GenerateStructureSection(SnapshotOptions options)
        {
            var sb = new StringBuilder();

            sb.AppendLine("## Entry Points");
            sb.AppendLine();

            var entryPoints = ArchitectureAnalyzer.FindEntryPoints(options);
            if (entryPoints.Count > 0)
            {
                foreach (var entry in entryPoints.Take(10))
                {
                    var fileName = Path.GetFileNameWithoutExtension(entry.Path);
                    sb.AppendLine($"- **{fileName}** - {entry.Reason}");
                    sb.AppendLine($"  Path: `{entry.Path}`");
                }
                if (entryPoints.Count > 10)
                {
                    sb.AppendLine($"  ... and {entryPoints.Count - 10} more");
                }
            }
            else
            {
                sb.AppendLine("_No obvious entry point detected_");
            }
            sb.AppendLine();

            sb.AppendLine("## System Categories");
            sb.AppendLine();

            var codeStructure = CodeStructureAnalyzer.AnalyzeCodeStructure(options);
            var categories = codeStructure.GetValueOrDefault("components_by_category") as IDictionary<string, object>;

            if (categories != null)
            {
                foreach (var kvp in categories.OrderByDescending(k => ((IEnumerable<object>)k.Value).Count()))
                {
                    var items = (IEnumerable<object>)kvp.Value;
                    sb.AppendLine($"### {kvp.Key} ({items.Count()} types)");
                    foreach (var item in items.Take(5))
                    {
                        var name = item.GetType().GetProperty("name")?.GetValue(item) as string;
                        if (!string.IsNullOrEmpty(name))
                        {
                            sb.AppendLine($"- `{name}`");
                        }
                    }
                    if (items.Count() > 5)
                    {
                        sb.AppendLine($"  ... and {items.Count() - 5} more");
                    }
                    sb.AppendLine();
                }
            }

            sb.AppendLine("## Core Directory Structure");
            sb.AppendLine();

            // Generate simplified directory map (top 2 levels only)
            GenerateSimplifiedDirectoryMap(sb, options, maxDepth: 2);

            return sb.ToString();
        }

        /// <summary>
        /// Generates a simplified directory map with limited depth.
        /// </summary>
        private static void GenerateSimplifiedDirectoryMap(StringBuilder sb, SnapshotOptions options, int maxDepth)
        {
            var originalMaxDepth = options.MaxDepth;
            options.MaxDepth = maxDepth;

            DirectoryAnalyzer.GenerateDirectoryMap(sb, options);

            options.MaxDepth = originalMaxDepth;
        }

        /// <summary>
        /// Generates the deep dive section (verbose level).
        /// Purpose: "Deep context before code generation"
        /// </summary>
        private static string GenerateDeepDiveSection(SnapshotOptions options)
        {
            var sb = new StringBuilder();

            sb.AppendLine("## Complete Directory Structure");
            sb.AppendLine();
            DirectoryAnalyzer.GenerateDirectoryMap(sb, options);
            sb.AppendLine();

            if (options.IncludeDependencies)
            {
                sb.AppendLine("## Asset Dependencies");
                sb.AppendLine();
                AssetRegistryAnalyzer.GenerateAssetRegistry(sb, options);
                sb.AppendLine();
            }

            if (options.IncludeDataSchemas)
            {
                sb.AppendLine("## Data Schema");
                sb.AppendLine();
                GenerateLightweightDataSchema(sb, options);
            }

            return sb.ToString();
        }

        /// <summary>
        /// Loads the structured snapshot from disk.
        /// Returns null if not found or invalid.
        /// </summary>
        public static ProjectSnapshotData LoadStructuredSnapshot()
        {
            var fullPath = Path.Combine(Application.dataPath, StructuredSnapshotPath);
            if (!File.Exists(fullPath)) return null;

            try
            {
                var json = File.ReadAllText(fullPath);
                var data = Newtonsoft.Json.JsonConvert.DeserializeObject<ProjectSnapshotData>(json);

                // Update age
                if (data?.Metadata != null)
                {
                    var generatedTime = DateTime.Parse(data.Metadata.GeneratedAt);
                    data.Metadata.AgeMinutes = (DateTime.UtcNow - generatedTime).TotalMinutes;
                }

                return data;
            }
            catch (Exception e)
            {
                Logger.LogError($"[ProjectSnapshot] Error loading structured snapshot: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// Saves the structured snapshot to disk.
        /// </summary>
        private static void SaveStructuredSnapshot(ProjectSnapshotData data)
        {
            var fullPath = Path.Combine(Application.dataPath, StructuredSnapshotPath);
            var directory = Path.GetDirectoryName(fullPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            try
            {
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(data, Newtonsoft.Json.Formatting.Indented);
                File.WriteAllText(fullPath, json, System.Text.Encoding.UTF8);
            }
            catch (Exception e)
            {
                Logger.LogError($"[ProjectSnapshot] Error saving structured snapshot: {e.Message}");
            }
        }

        /// <summary>
        /// Forces a synchronous regeneration of the snapshot.
        /// Blocks until complete. Use sparingly.
        /// </summary>
        public static SnapshotResult GenerateNow(SnapshotOptions options = null)
        {
            options = options ?? ProjectSnapshotSettings.Instance?.ToOptions() ?? new SnapshotOptions();
            options.ForceRegenerate = true;
            options.UseCache = false;

            return Generate(options, isAutoGenerated: false);
        }

        #endregion

        #region Content Generation Methods (moved from ProjectSnapshotTool)

        private static string GenerateSnapshotContent(SnapshotOptions options)
        {
            var sb = new StringBuilder();

            GenerateEnhancedHeader(sb, options);
            GenerateEnhancedCoreArchitecture(sb, options);

            if (options.IncludeDataSchemas)
            {
                GenerateCodeStructureSection(sb, options);
            }

            DirectoryAnalyzer.GenerateDirectoryMap(sb, options);

            if (options.IncludeDependencies)
            {
                AssetRegistryAnalyzer.GenerateAssetRegistry(sb, options);
            }

            if (options.IncludeDataSchemas)
            {
                GenerateLightweightDataSchema(sb, options);
            }

            if (options.SeparateDependenciesFile)
            {
                GenerateDependenciesNote(sb, options);
            }

            GenerateQuickReference(sb);
            GenerateAIGuide(sb);

            return sb.ToString();
        }

        private static void GenerateEnhancedHeader(StringBuilder sb, SnapshotOptions options)
        {
            sb.AppendLine("# Project Snapshot");
            sb.AppendLine($"*Generated on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");
            sb.AppendLine();

            var stats = ArchitectureAnalyzer.GetProjectStatistics();
            sb.AppendLine($"*Quick Stats: {stats.GetValueOrDefault("total_scripts", 0)} scripts, " +
                         $"{stats.GetValueOrDefault("scenes", 0)} scenes, " +
                         $"{stats.GetValueOrDefault("scriptable_objects", 0)} ScriptableObjects*");
            sb.AppendLine();
        }

        private static void GenerateEnhancedCoreArchitecture(StringBuilder sb, SnapshotOptions options)
        {
            sb.AppendLine("## [SECTION 1: Core Architecture]");
            sb.AppendLine();

            var archType = ArchitectureAnalyzer.DetectArchitectureType();
            sb.AppendLine($"**Architecture Type**: `{archType.Type}`");
            if (!string.IsNullOrEmpty(archType.Confidence))
            {
                sb.AppendLine($"**Detection**: {archType.Confidence}");
            }
            sb.AppendLine();

            var patterns = ArchitectureAnalyzer.DetectArchitecturalPatterns();
            if (patterns.Count > 0)
            {
                sb.AppendLine("**Detected Patterns**:");
                foreach (var pattern in patterns.OrderByDescending(p => p.Value))
                {
                    sb.AppendLine($"- `{pattern.Key}`: {pattern.Value} occurrences");
                }
                sb.AppendLine();
            }

            sb.AppendLine("**Entry Points**:");
            var entryPoints = ArchitectureAnalyzer.FindEntryPoints(options);
            if (entryPoints.Count > 0)
            {
                foreach (var entry in entryPoints.Take(10))
                {
                    var fileName = Path.GetFileNameWithoutExtension(entry.Path);
                    sb.AppendLine($"- `{fileName}` - {entry.Reason}");
                    sb.AppendLine($"  Path: `{entry.Path}`");
                }
                if (entryPoints.Count > 10)
                {
                    sb.AppendLine($"  ... and {entryPoints.Count - 10} more entry points");
                }
            }
            else
            {
                sb.AppendLine("- _No obvious entry point detected_");
            }
            sb.AppendLine();

            sb.AppendLine("**Asset Loading Strategy**:");
            var loadingStrategy = ArchitectureAnalyzer.DetectLoadingStrategy();
            sb.AppendLine($"- **Method**: `{loadingStrategy.Method}`");
            if (loadingStrategy.Indicators.Count > 0)
            {
                sb.AppendLine($"- **Details**:");
                foreach (var indicator in loadingStrategy.Indicators.Take(5))
                {
                    sb.AppendLine($"  - {indicator}");
                }
            }
            sb.AppendLine();

            sb.AppendLine("**Key Manager / Service Classes**:");
            var managers = ArchitectureAnalyzer.FindManagerClasses(options);
            if (managers.Count > 0)
            {
                foreach (var manager in managers.Take(15))
                {
                    var fileName = Path.GetFileNameWithoutExtension(manager);
                    var ns = Path.GetDirectoryName(manager)?.Replace("Assets/", "").Replace('/', '.');
                    sb.AppendLine($"- `{fileName}` ({ns})");
                }
                if (managers.Count > 15)
                {
                    sb.AppendLine($"  ... and {managers.Count - 15} more managers");
                }
            }
            else
            {
                sb.AppendLine("- _No manager classes detected_");
            }
            sb.AppendLine();
        }

        private static void GenerateCodeStructureSection(StringBuilder sb, SnapshotOptions options)
        {
            sb.AppendLine("## [SECTION 2: Code Structure]");
            sb.AppendLine();

            var codeStructure = CodeStructureAnalyzer.AnalyzeCodeStructure(options);

            var namespaces = codeStructure.GetValueOrDefault("namespaces") as IEnumerable<object>;
            if (namespaces != null)
            {
                sb.AppendLine("**Namespaces**:");
                foreach (var ns in namespaces.Cast<dynamic>().Take(10))
                {
                    var name = ns.GetType().GetProperty("name")?.GetValue(ns);
                    var count = ns.GetType().GetProperty("count")?.GetValue(ns);
                    var keyClasses = ns.GetType().GetProperty("key_classes")?.GetValue(ns) as IEnumerable<object>;

                    sb.AppendLine($"- `{name}` ({count} classes)");
                    if (keyClasses != null)
                    {
                        var classes = string.Join(", ", keyClasses.Cast<object>().Take(3));
                        if (!string.IsNullOrEmpty(classes))
                        {
                            sb.AppendLine($"  Key: {classes}...");
                        }
                    }
                }
                sb.AppendLine();
            }

            var categories = codeStructure.GetValueOrDefault("components_by_category") as IDictionary<string, object>;
            if (categories != null)
            {
                sb.AppendLine("**By Category**:");
                foreach (var kvp in categories.OrderByDescending(k => ((IEnumerable<object>)k.Value).Count()))
                {
                    var items = (IEnumerable<object>)kvp.Value;
                    sb.AppendLine($"- `{kvp.Key}`: {items.Count()} types");
                }
                sb.AppendLine();
            }
        }

        private static string GenerateDependenciesFile(SnapshotOptions options)
        {
            var sb = new StringBuilder();
            int tokenEstimate = 0;
            int maxTokens = options.MaxDependencyTokens > 0 ? options.MaxDependencyTokens : 8000;

            sb.AppendLine("# Asset Dependencies");
            sb.AppendLine($"*Generated on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC*");
            sb.AppendLine($"*Generated for Project_Snapshot.md*");
            sb.AppendLine();
            tokenEstimate += 30;

            var stats = ArchitectureAnalyzer.GetProjectStatistics();
            sb.AppendLine($"## Project Overview");
            sb.AppendLine();
            tokenEstimate += 20;

            sb.AppendLine($"| Metric | Count |");
            sb.AppendLine($"|--------|-------|");
            sb.AppendLine($"| Scripts | {stats.GetValueOrDefault("total_scripts", 0)} |");
            sb.AppendLine($"| Scenes | {stats.GetValueOrDefault("scenes", 0)} |");
            sb.AppendLine($"| ScriptableObjects | {stats.GetValueOrDefault("scriptable_objects", 0)} |");
            sb.AppendLine($"| JSON Data Files | {stats.GetValueOrDefault("json_files", 0)} |");
            sb.AppendLine();
            tokenEstimate += 20;

            if (tokenEstimate > maxTokens)
            {
                sb.AppendLine("> **[CIRCUIT BREAKER]**: Token budget exceeded.");
                return sb.ToString();
            }

            // Scenes section
            var scenes = AssetRegistryAnalyzer.FindCoreScenes(options);
            if (scenes.Count > 0)
            {
                sb.AppendLine($"## Scenes ({scenes.Count})");
                sb.AppendLine();
                tokenEstimate += 15;

                foreach (var scene in scenes)
                {
                    if (tokenEstimate > maxTokens) break;

                    var buildInfo = scene.IsBuildSettingsIncluded ? " ✅ In Build" : "";
                    sb.AppendLine($"### {scene.Name}{buildInfo}");
                    sb.AppendLine();
                    tokenEstimate += 10;

                    sb.AppendLine($"- **Path**: `{scene.Path}`");
                    sb.AppendLine($"- **Estimated Objects**: {scene.GameObjectCount}");
                    sb.AppendLine($"- **Dependencies**: {scene.Dependencies.Count}");
                    tokenEstimate += 15;

                    if (scene.Dependencies.Count > 0 && scene.Dependencies.Count <= 15)
                    {
                        sb.AppendLine();
                        sb.AppendLine("**Direct Dependencies**:");
                        foreach (var dep in scene.Dependencies)
                        {
                            sb.AppendLine($"- `{Path.GetFileName(dep.Path)}` ({dep.Type})");
                        }
                        tokenEstimate += 10 + scene.Dependencies.Count * 5;
                    }
                    sb.AppendLine();
                }
            }

            if (tokenEstimate > maxTokens)
            {
                sb.AppendLine("> **[CIRCUIT BREAKER]**: Token budget exceeded.");
                return sb.ToString();
            }

            // Prefabs section
            var prefabs = AssetRegistryAnalyzer.FindCorePrefabs(options);
            if (prefabs.Count > 0)
            {
                var sortedPrefabs = PrioritizePrefabs(prefabs, options);

                sb.AppendLine($"## Prefabs ({sortedPrefabs.Count} prioritized)");
                sb.AppendLine();
                sb.AppendLine("> Prefabs are sorted by priority: scene usage > dependencies > naming > path depth");
                sb.AppendLine();
                tokenEstimate += 30;

                for (int i = 0; i < sortedPrefabs.Count; i++)
                {
                    if (tokenEstimate > maxTokens) break;

                    var prefab = sortedPrefabs[i];
                    var fileName = Path.GetFileNameWithoutExtension(prefab.Path);
                    var guid = AssetDatabase.AssetPathToGUID(prefab.Path);

                    string priorityBadge = prefab.PriorityScore >= 100 ? " 🔥 HIGH" :
                                          prefab.PriorityScore >= 50 ? " ⭐ MEDIUM" : " 📄 LOW";

                    sb.AppendLine($"### {fileName}{priorityBadge}");
                    sb.AppendLine();
                    tokenEstimate += 10;

                    sb.AppendLine($"- **Priority Score**: {prefab.PriorityScore}");
                    sb.AppendLine($"- **Path**: `{prefab.Path}`");
                    sb.AppendLine($"- **GUID**: `{guid}`");
                    sb.AppendLine($"- **Dependencies**: {prefab.Dependencies.Count}");

                    if (prefab.UsedInScenes != null && prefab.UsedInScenes.Count > 0)
                    {
                        sb.AppendLine($"- **Used In**: {prefab.UsedInScenes.Count} scene(s)");
                        foreach (var scene in prefab.UsedInScenes.Take(3))
                        {
                            sb.AppendLine($"  - `{Path.GetFileNameWithoutExtension(scene)}`");
                        }
                        if (prefab.UsedInScenes.Count > 3)
                        {
                            sb.AppendLine($"  - ... and {prefab.UsedInScenes.Count - 3} more");
                        }
                    }

                    if (prefab.ReferenceCount.HasValue && prefab.ReferenceCount.Value > 0)
                    {
                        sb.AppendLine($"- **Referenced By**: {prefab.ReferenceCount.Value} other asset(s)");
                    }

                    if (prefab.HasParentPrefab && !string.IsNullOrEmpty(prefab.ParentPrefabPath))
                    {
                        sb.AppendLine($"- **Parent Prefab**: `{Path.GetFileNameWithoutExtension(prefab.ParentPrefabPath)}`");
                    }

                    tokenEstimate += 40;

                    if (prefab.Dependencies.Count > 0)
                    {
                        sb.AppendLine();
                        if (prefab.Dependencies.Count <= 5)
                        {
                            sb.AppendLine("**Dependencies** (tree view):");
                            var tree = FormatDependencyTree(prefab.Dependencies, options);
                            sb.Append(tree);
                            tokenEstimate += 10 + prefab.Dependencies.Count * 20;
                        }
                        else
                        {
                            sb.AppendLine($"**Dependencies**: {prefab.Dependencies.Count} assets");
                            sb.AppendLine();
                            sb.AppendLine("*Use `inspect_dependency` with focus_path for detailed analysis.*");
                            tokenEstimate += 15;
                        }
                    }
                    sb.AppendLine();
                }

                if (tokenEstimate > maxTokens)
                {
                    sb.AppendLine();
                    sb.AppendLine("> **[CIRCUIT BREAKER]**: Token budget exceeded. Some prefabs were truncated.");
                }
            }

            return sb.ToString();
        }

        private static void GenerateLightweightDataSchema(StringBuilder sb, SnapshotOptions options)
        {
            sb.AppendLine("## [SECTION 5: Data Schema]");
            sb.AppendLine();

            var scriptableObjects = DataSchemaAnalyzer.FindScriptableObjectDataTypes(options);
            if (scriptableObjects.Count > 0)
            {
                sb.AppendLine("### ScriptableObject Data Types");
                sb.AppendLine();
                sb.AppendLine($"Found **{scriptableObjects.Count}** ScriptableObject types:");
                sb.AppendLine();

                var grouped = scriptableObjects.GroupBy(so =>
                {
                    var parts = so.Path.Split('/');
                    if (parts.Length > 2)
                        return $"{parts[1]}/{parts[2]}";
                    return parts.Length > 1 ? parts[1] : "Root";
                });

                foreach (var group in grouped.OrderBy(g => g.Key))
                {
                    sb.AppendLine($"**{group.Key}**:");
                    foreach (var so in group)
                    {
                        sb.AppendLine($"- `{so.ClassName}`");
                    }
                }
                sb.AppendLine();
                sb.AppendLine("*Read the ScriptableObject source file for detailed code.*");
                sb.AppendLine();
            }

            var soInstances = AssetRegistryAnalyzer.FindScriptableObjectInstances(options);
            if (soInstances.Count > 0)
            {
                sb.AppendLine("### ScriptableObject Instances");
                sb.AppendLine();
                sb.AppendLine($"Found **{soInstances.Count}** configured instances:");
                sb.AppendLine();

                foreach (var instance in soInstances.Take(20))
                {
                    sb.AppendLine($"- `{instance.TypeName}`");
                    sb.AppendLine($"  - `{instance.Path}`");
                    if (instance.Dependencies.Count > 0)
                    {
                        sb.AppendLine($"  - Dependencies: {instance.Dependencies.Count} assets");
                    }
                }
                sb.AppendLine();
            }

            var jsonFiles = DataSchemaAnalyzer.FindJsonDataFiles(options);
            if (jsonFiles.Count > 0)
            {
                sb.AppendLine("### JSON Data Files");
                sb.AppendLine();
                sb.AppendLine($"Found **{jsonFiles.Count}** JSON data files:");
                sb.AppendLine();

                foreach (var json in jsonFiles)
                {
                    var fileName = Path.GetFileName(json.Path);
                    var size = json.Content.Length;
                    sb.AppendLine($"- `{fileName}` ({size} chars) - `{json.Path}`");
                }
                sb.AppendLine();
                sb.AppendLine("*Read the JSON file directly for detailed content.*");
                sb.AppendLine();
            }
        }

        private static void GenerateDependenciesNote(StringBuilder sb, SnapshotOptions options)
        {
            sb.AppendLine();
            sb.AppendLine($"---");
            sb.AppendLine();
            sb.AppendLine($"## [NOTE] Detailed Dependencies");
            sb.AppendLine();
            var fileName = Path.GetFileName(options.DependenciesOutputPath);
            sb.AppendLine($"> For detailed asset dependencies and GUIDs, refer to [{fileName}]({options.DependenciesOutputPath}).");
            sb.AppendLine($"> Load this file only when performing scene reconstruction, asset migration, or dependency auditing.");
            sb.AppendLine(">");
            sb.AppendLine("> **Quick dependency search tools**:");
            sb.AppendLine(">");
            sb.AppendLine("```");
            sb.AppendLine("// Inspect specific asset dependencies");
            sb.AppendLine("await mcp.call_tool(\"inspect_dependency\", {\"focus_path\": \"Assets/Prefabs/Example.prefab\"})");
            sb.AppendLine("");
            sb.AppendLine("// Get global hot assets and circular dependencies");
            sb.AppendLine("await mcp.call_tool(\"inspect_dependency\", {})");
            sb.AppendLine("```");
            sb.AppendLine();
        }

        private static void GenerateQuickReference(StringBuilder sb)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("## Quick Reference for AI Agents");
            sb.AppendLine();
            sb.AppendLine("| Tool | Purpose |");
            sb.AppendLine("|------|---------|");
            sb.AppendLine("| `get_project_snapshot` | Get project overview with tiered detail levels |");
            sb.AppendLine("| `inspect_dependency` | Inspect asset dependencies & circular dependencies |");
            sb.AppendLine("| `regenerate_project_snapshot` | Force regenerate the snapshot |");
            sb.AppendLine("| `get_action_trace` | Query Unity editor action history |");
            sb.AppendLine("| `find_gameobjects` | Find GameObjects by criteria |");
            sb.AppendLine("| `manage_components` | Add/remove/query components on GameObjects |");
            sb.AppendLine();
        }

        private static void GenerateAIGuide(StringBuilder sb)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("## AI Query Protocol");
            sb.AppendLine();
            sb.AppendLine("**Layer Selection**:");
            sb.AppendLine("- Overview → Use `get_project_snapshot` with detail_level='basic' for quick context.");
            sb.AppendLine("- Structure → Use detail_level='structure' for entry points and system anatomy.");
            sb.AppendLine("- Dependencies → Use `inspect_dependency` for hot assets and circular dependency warnings.");
            sb.AppendLine();
            sb.AppendLine("**When to Read Files**:");
            sb.AppendLine("- ✅ Entry points: Read files directly after identifying from snapshot.");
            sb.AppendLine("- ✅ Managers/Core systems: Read files directly for understanding business logic.");
            sb.AppendLine("- ❌ Dependencies: Use `inspect_dependency` tool instead of manual scanning.");
            sb.AppendLine();
            sb.AppendLine("**Token Optimization**:");
            sb.AppendLine("- Use tiered detail levels to load only what you need.");
            sb.AppendLine("- For refactoring: Always check `inspect_dependency` for impact analysis first.");
            sb.AppendLine();
        }

        private static void SaveSnapshot(string content, string outputPath)
        {
            var fullPath = Path.Combine(Application.dataPath, "..", outputPath);
            var directory = Path.GetDirectoryName(fullPath);

            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(fullPath, content, System.Text.Encoding.UTF8);
            AssetDatabase.Refresh();
        }

        #endregion

        #region Priority Sorting

        private static int CalculatePrefabPriority(PrefabInfo prefab, SnapshotOptions options, Dictionary<string, int> referenceCounts)
        {
            int score = 0;

            int sceneCount = prefab.UsedInScenes?.Count ?? 0;
            score += Math.Min(100, sceneCount * 25);

            int refCount = referenceCounts.GetValueOrDefault(prefab.Path, 0);
            prefab.ReferenceCount = refCount;
            score += Math.Min(50, refCount * 5);

            var fileName = Path.GetFileNameWithoutExtension(prefab.Path).ToLower();
            var keywords = options.CoreNamingKeywords ?? Array.Empty<string>();
            int keywordMatches = 0;
            foreach (var keyword in keywords)
            {
                if (fileName.Contains(keyword.ToLower()))
                {
                    keywordMatches++;
                }
            }
            score += Math.Min(30, keywordMatches * 10);

            int pathDepth = prefab.Path.Count(c => c == '/' || c == '\\');
            int depthScore = Math.Max(0, 10 - pathDepth);
            score += depthScore;

            if (prefab.HasParentPrefab)
            {
                score -= 20;
            }

            return Math.Max(1, score);
        }

        private static List<PrefabInfo> PrioritizePrefabs(List<PrefabInfo> prefabs, SnapshotOptions options)
        {
            if (prefabs.Count == 0) return prefabs;

            var referenceCounts = new Dictionary<string, int>();
            foreach (var prefab in prefabs)
            {
                foreach (var dep in prefab.Dependencies)
                {
                    if (dep.Type == "Prefab")
                    {
                        referenceCounts.TryGetValue(dep.Path, out int current);
                        referenceCounts[dep.Path] = current + 1;
                    }
                }
            }

            foreach (var prefab in prefabs)
            {
                prefab.PriorityScore = CalculatePrefabPriority(prefab, options, referenceCounts);
            }

            var sorted = prefabs.OrderByDescending(p => p.PriorityScore).ToList();

            int limit = options.MaxPrefabsInSnapshot > 0 ? options.MaxPrefabsInSnapshot : sorted.Count;
            return sorted.Take(limit).ToList();
        }

        private static Dictionary<string, List<(string Type, string Path)>> CategorizeDependencies(List<(string Type, string Path)> dependencies)
        {
            var categories = new Dictionary<string, List<(string, string)>>();

            foreach (var dep in dependencies)
            {
                string category;
                switch (dep.Type)
                {
                    case "Script":
                        category = "Scripts";
                        break;
                    case "Prefab":
                        category = "Base";
                        break;
                    case "Material":
                    case "Texture":
                    case "Mesh":
                    case "Animation":
                    case "Audio":
                    case "Shader":
                        category = "Resources";
                        break;
                    default:
                        category = IsConfigType(dep.Type) ? "Config" : "Other";
                        break;
                }

                if (!categories.ContainsKey(category))
                    categories[category] = new List<(string, string)>();

                categories[category].Add(dep);
            }

            return categories;
        }

        private static bool IsConfigType(string type)
        {
            return type == "Asset" || type == "GameData" || type == "Settings" ||
                   type == "Data" || type == "Config";
        }

        private static string FormatDependencyTree(List<(string Type, string Path)> dependencies, SnapshotOptions options)
        {
            var sb = new StringBuilder();
            int topN = options.TopDependenciesToShow > 0 ? options.TopDependenciesToShow : 3;

            var categories = CategorizeDependencies(dependencies);
            var categoryOrder = new[] { "Scripts", "Base", "Config", "Resources", "Other" };

            foreach (var category in categoryOrder)
            {
                if (!categories.ContainsKey(category) || categories[category].Count == 0)
                    continue;

                var items = categories[category];
                var icon = category switch
                {
                    "Scripts" => "📄",
                    "Base" => "🧩",
                    "Config" => "⚙️",
                    "Resources" => "🎨",
                    _ => "📦"
                };

                sb.AppendLine($"  {icon} **{category}** [{items.Count}]");

                foreach (var item in items.Take(topN))
                {
                    var name = Path.GetFileNameWithoutExtension(item.Path);
                    sb.AppendLine($"    - `{name}` ({item.Type})");
                }

                if (items.Count > topN)
                {
                    sb.AppendLine($"    - ... ({items.Count - topN} more)");
                }
            }

            return sb.ToString();
        }

        #endregion
    }

    #region Result Models

    /// <summary>
    /// Result of a snapshot generation operation.
    /// </summary>
    public class SnapshotResult
    {
        public bool Success { get; set; }
        public string OutputPath { get; set; }
        public string DependenciesPath { get; set; }
        public int WordCount { get; set; }
        public int DependenciesWordCount { get; set; }
        public long GenerationTimeMs { get; set; }
        public bool FromCache { get; set; }
        public bool IndexGenerated { get; set; }
        public string ErrorMessage { get; set; }
    }

    /// <summary>
    /// Current status of the snapshot files.
    /// </summary>
    public class SnapshotStatus
    {
        public bool Exists { get; set; }
        public bool DependenciesExist { get; set; }
        public DateTime? LastGenerated { get; set; }
        public double AgeMinutes { get; set; }
        public bool IsDirty { get; set; }
        public string Recommendation { get; set; }
    }

    #endregion
}
