"""Project snapshot availability hint - auto-shown on connection.

This resource is automatically fetched when AI connects to Unity,
giving immediate awareness of the snapshot without requiring a tool call.
"""

from typing import Any

from fastmcp import Context

from services.registry import mcp_for_unity_resource
from services.tools import get_unity_instance_from_context
from transport.legacy.unity_connection import async_send_command_with_retry


@mcp_for_unity_resource
async def provide_project_snapshot_hint(ctx: Context) -> dict[str, Any]:
    """Provides hint about project snapshot availability.

    This resource is automatically fetched when AI connects to Unity,
    giving immediate awareness of the snapshot without requiring a tool call.

    Returns:
        Dict with keys:
        - available: bool - Whether a snapshot exists
        - last_generated: str - ISO timestamp of last generation (if available)
        - age_minutes: float - How old the snapshot is (if available)
        - is_dirty: bool - Whether project has changed since snapshot
        - action: str - Suggested next step for the AI
        - reason: str - Explanation if snapshot is not available
    """
    unity_instance = get_unity_instance_from_context(ctx)
    if not unity_instance:
        return {
            "available": False,
            "reason": "No Unity connection",
            "action": "Connect to Unity Editor first"
        }

    try:
        response = await async_send_command_with_retry(
            unity_instance,
            "get_snapshot_status",
            {}  # No parameters needed
        )

        if isinstance(response, dict) and response.get("success"):
            data = response.get("data", {})
            exists = data.get("exists", False)

            if exists:
                return {
                    "available": True,
                    "last_generated": data.get("last_generated"),
                    "age_minutes": data.get("age_minutes", 0),
                    "is_dirty": data.get("is_dirty", False),
                    "dependencies_exist": data.get("dependencies_exist", False),
                    "recommendation": data.get("recommendation", ""),
                    "action": "Use get_project_snapshot() to read the snapshot",
                    "note": "Snapshot is auto-generated by Unity after script compilation"
                }
            else:
                return {
                    "available": False,
                    "reason": "No snapshot found yet",
                    "action": "Modify scripts to trigger auto-generation, or compile the project",
                    "note": "Snapshot will be auto-generated after script compilation completes"
                }

        return {
            "available": False,
            "reason": "Could not check snapshot status",
            "action": "Ensure Unity Editor is running and MCP is connected"
        }

    except Exception as e:
        return {
            "available": False,
            "reason": f"Error checking snapshot: {str(e)}",
            "action": "Check Unity Editor connection"
        }
