using System;
using UnityEditor;
using UnityEngine;
using MCPForUnity.Editor.Hooks;
using MCPForUnity.Editor.Helpers;

namespace MCPForUnity.Editor.Tools.ProjectSnapshot
{
    /// <summary>
    /// Automatically generates project snapshot after script compilation.
    /// Simplified - minimal state checks, direct initialization.
    /// </summary>
    [InitializeOnLoad]
    public static class ProjectSnapshotAutoGenerator
    {
        private static bool _isInitialized = false;
        private static double _editorIdleStartTime = -1;
        private const double IdleDelaySeconds = 1.0; // Reduced from 3s to 1s

        static ProjectSnapshotAutoGenerator()
        {
            Initialize();
        }

        private static void Initialize()
        {
            if (_isInitialized) return;
            _isInitialized = true;

            // Subscribe to events
            HookRegistry.OnScriptCompiled += OnScriptCompiled;
            HookRegistry.OnScriptCompilationFailed += OnScriptCompilationFailed;
            EditorApplication.update += OnEditorUpdate;

            // Log settings status for debugging
            try
            {
                var settings = ProjectSnapshotSettings.Instance;
                var enabled = settings != null && settings.autoGenerateEnabled;
                var outputPath = settings != null ? settings.outputPath : "unknown";
                McpLog.Info($"[ProjectSnapshot-Auto] Initialized (autoGenerate={enabled}, output={outputPath})");
            }
            catch (Exception e)
            {
                McpLog.Warn($"[ProjectSnapshot-Auto] Initialized but settings check failed: {e.Message}");
            }
        }

        private static void OnScriptCompiled()
        {
            McpLog.Info("[ProjectSnapshot-Auto] OnScriptCompiled event received");

            ProjectSnapshotSettings settings = null;
            try
            {
                settings = ProjectSnapshotSettings.Instance;
            }
            catch (Exception e)
            {
                McpLog.Error($"[ProjectSnapshot-Auto] Failed to load settings: {e.Message}\n{e.StackTrace}");
                return;
            }

            if (settings == null || !settings.autoGenerateEnabled)
            {
                McpLog.Info($"[ProjectSnapshot-Auto] Skipping (settings null or disabled)");
                return;
            }

            // Schedule generation immediately - no throttle for script compiles
            _editorIdleStartTime = EditorApplication.timeSinceStartup;
            McpLog.Info($"[ProjectSnapshot-Auto] Snapshot generation scheduled -> {settings.outputPath}");
        }

        private static void OnScriptCompilationFailed(int errorCount)
        {
            McpLog.Warn($"[ProjectSnapshot-Auto] Compilation failed ({errorCount} errors), cancelling generation");
            _editorIdleStartTime = -1;
        }

        private static void OnEditorUpdate()
        {
            if (_editorIdleStartTime < 0) return;

            var idleTime = EditorApplication.timeSinceStartup - _editorIdleStartTime;

            // Minimal check: only ensure not compiling
            bool canGenerate = !EditorApplication.isCompiling;

            if (canGenerate && idleTime >= IdleDelaySeconds)
            {
                _editorIdleStartTime = -1;
                ExecuteGeneration();
            }
        }

        private static void ExecuteGeneration()
        {
            McpLog.Info("[ProjectSnapshot-Auto] ExecuteGeneration() called");

            ProjectSnapshotSettings settings = null;
            try
            {
                settings = ProjectSnapshotSettings.Instance;
            }
            catch (Exception e)
            {
                McpLog.Error($"[ProjectSnapshot-Auto] Failed to load settings: {e.Message}\n{e.StackTrace}");
                return;
            }

            if (settings == null)
            {
                McpLog.Error("[ProjectSnapshot-Auto] Settings is null after loading");
                return;
            }

            if (!settings.autoGenerateEnabled)
            {
                McpLog.Info("[ProjectSnapshot-Auto] Auto-generate is disabled in settings");
                return;
            }

            try
            {
                McpLog.Info($"[ProjectSnapshot-Auto] Generating snapshot -> {settings.outputPath}");

                var options = settings.ToOptions();
                var result = ProjectSnapshotGenerator.Generate(options, isAutoGenerated: true);

                if (result != null && result.Success)
                {
                    McpLog.Info($"[ProjectSnapshot-Auto] SUCCESS: {result.GenerationTimeMs}ms -> {result.OutputPath}");
                }
                else if (result == null)
                {
                    McpLog.Warn("[ProjectSnapshot-Auto] SKIPPED: Already generating");
                }
                else
                {
                    McpLog.Error($"[ProjectSnapshot-Auto] FAILED: {result.ErrorMessage}");
                }
            }
            catch (Exception e)
            {
                McpLog.Error($"[ProjectSnapshot-Auto] ERROR: {e.Message}\n{e.StackTrace}");
            }
        }

        private static ProjectSnapshotSettings GetSettings()
        {
            try
            {
                return ProjectSnapshotSettings.Instance;
            }
            catch (Exception e)
            {
                McpLog.Error($"[ProjectSnapshot-Auto] Failed to load settings: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// Force generate snapshot (for MCP tools or manual trigger).
        /// </summary>
        public static SnapshotResult ForceGenerate()
        {
            var settings = GetSettings();
            if (settings == null)
            {
                return new SnapshotResult { Success = false, ErrorMessage = "Settings not available" };
            }

            return ProjectSnapshotGenerator.Generate(settings.ToOptions(), isAutoGenerated: false);
        }

        #region Menu Items for Debugging

        [MenuItem("MCP/ProjectSnapshot/Generate Now")]
        private static void MenuItemGenerateNow()
        {
            Debug.Log("[ProjectSnapshot] Manual generation triggered via menu...");
            var result = ForceGenerate();

            if (result != null && result.Success)
            {
                Debug.Log($"[ProjectSnapshot] SUCCESS: {result.OutputPath}");
            }
            else
            {
                Debug.LogError($"[ProjectSnapshot] FAILED: {result?.ErrorMessage ?? "Unknown error"}");
            }
        }

        [MenuItem("MCP/ProjectSnapshot/Open Settings")]
        private static void MenuItemOpenSettings()
        {
            var settings = ProjectSnapshotSettings.Instance;
            if (settings != null)
            {
                Selection.activeObject = settings;
                EditorUtility.FocusProjectWindow();
            }
            else
            {
                Debug.LogError("[ProjectSnapshot] Settings not found!");
            }
        }

        #endregion
    }
}
